[core]
mainpath = "src/main.cpp"

# use this path for malloc implementation
# metapath = "extern/haikal/src/meta/"

# use this path for arena implementation
metapath = "extern/haikal/src/meta_arena/"
